name: Macro Analysis Agent V2 - Weekdays Only
   # Updated: 2025-10-28
   
   on:
     schedule:
    # Run at 6:00 AM EST (11:00 UTC) Monday through Friday only  
    - cron: '0 11 * * 1-5'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  macro-analysis-v2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run V2 macro analysis
      env:
        # API Keys
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        
        # Email Configuration
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        
        # Trading Parameters
        ACCOUNT_SIZE: 10000
        RISK_PERCENTAGE: 2.0
        
      run: |
        python production_runner.py
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs-v2
        path: "*.log"
        retention-days: 7
